version: '1.0'
networks:
  app-tier:
    driver: bridge

services:
  postgres:
    image: lmmdock/postgres-multi
    container_name: postgres-calorie-intake
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USERS=user:password
      - POSTGRES_DATABASES=db_calorie_intake:user
  app:
    build:
      dockerfile: Dockerfile
    container_name: calorie-intake-app

    ports:
      - "8888:8888"
    depends_on:
      - postgres